### ISSUE TITLE
testplan ui-generated JSON report for test_plan.view the json report in browser:Cannot view the browser

### ISSUE THREAD

**Issue by hemapriya123-sys** [Morgan-Stanley/testplan#258]
i run test plan using command python test_plan.py --ui.test runs and it prints in the terminal as Json generated at my folder .view the JSON report in browser:http://fe80::cd3e:db0e:1c79:867b%11:62434/testplan/local.but i could not see anything in browser.Please help to see testplan in ui

**Comment by ryan-collingham** [comment]
Looks like that might be a bug, the IP address you give looks like IPv6 so it should be enclosed in square brackets when printed to terminal. Can you try running again and insert square brackets into the URL manually like:

http://[fe80::cd3e:db0e:1c79:867b%11]:62434/testplan/local

And I think you should be able to see the UI.

So that we can fix the bug, could you provide us with more information about:

- Your OS type and version
- The version of Python you have installed (`python --version` output)
- What output do you get from running: `python -c "import socket; print(socket.gethostname())"`

Thanks for your interest in Testplan!

**Comment by hemapriya123-sys** [comment]
Thanks for your immediate response.

I tried manually with square bracket in URL.still the issue is same

information for bug fix:
1.Windows 7 professional
2.python 3.6.4
3.got my PC name 

could you ensure the command which i am giving for ui is correct or not?
If I run in cmd terminal,python test_plan.py --pdf x.pdf. I can view my report in pdf.
for UI,python test_plan.py --ui 
After my testplan runs,it outputs JSON generated at my folder called report.json.I can view it
view the JSON report in the browser:http://fe80::cd3e:db0e:1c79:867b%11:**56554**/testplan/local
but I cant view this url in browser and also every run it generates different number in the place of 56554.
Is there anything i need to give specific with --ui?

**Comment by hemapriya123-sys** [comment]
I forget to mention about the warning i receive,
![testplan](https://user-images.githubusercontent.com/54711670/64037254-75c4c800-cb55-11e9-9ac0-492c0850b496.jpg)

Please help as soon as possible to view tesplan in UI

**Comment by hemapriya123-sys** [comment]
I forget to mention this warning.
![testplan](https://user-images.githubusercontent.com/54711670/64037444-e66be480-cb55-11e9-933c-7f9bbdc31d08.jpg)

please help as soon as possible

**Comment by ryan-collingham** [comment]
Thanks for the information. First of all, don't worry about the warnings about command-line args being overridden, they are expected (we should remove them).

You are using the --ui mode correctly, it is just a bug in how we are formatting the address. The number that keeps changing is the port the UI server listens on - by default a random port is acquired each time, which is why it changes. A specific port can be set by adding a number after the --ui option.

There are a couple of things you can try. First, can you try running your testplan like:

`python test_plan.py --ui 45678`

Then when testplan prints "View the JSON report in the browser:", instead of copying the link, enter the following in your web browser to load the report:

http://[fe80::cd3e:db0e:1c79:867b]:45678/testplan/local

If that does not work, please try instead:

http://[fe80::cd3e:db0e:1c79:867b%11]:45678/testplan/local

Please let us know which (if any) of the two options above works for you, thanks!

**Comment by hemapriya123-sys** [comment]
Thanks for response.
Both options are not working still
http://[fe80::cd3e:db0e:1c79:867b]:45678/testplan/local:
This site can’t be reached [fe80::cd3e:db0e:1c79:867b] took too long to respond.
Search Google for [fe80 cd3e db0e 1c79 867b] 45678 test plan local
ERR_CONNECTION_TIMED_OUT

http://[fe80::cd3e:db0e:1c79:867b%11]:45678/testplan/local:
It goes for google search page to search  http://[fe80::cd3e:db0e:1c79:867b%11]:45678/testplan/local

Please provide if you have any other options to work in UI

**Comment by ryan-collingham** [comment]
Thanks for trying. The second option to try is to add the following code at the top of your testplan script:

```
from testplan import defaults
defaults.WEB_SERVER_HOSTNAME = 'localhost'
```

You should get a different URL when you then run `python test_plan.py --ui`, hopefully that URL should work.

**Comment by hemapriya123-sys** [comment]
Thanks a lot.It works.Great!

Very happy for your timely response.Thanks!

**Comment by ryan-collingham** [comment]
Great :+1:, no problem.

We should really change the default option so that it works "out of the box" without having to tweak the defaults, I'll leave this issue open until we fix that.

**Comment by ryan-collingham** [comment]
We've made a change to the latest master so that the UI mode should Just Work without needing to override the default web server hostname now.
